from django.conf.urls.defaults import *
from django.core.urlresolvers import reverse

urlpatterns = patterns('django.views.generic.simple',
    url(r'^Chapter$', 'redirect_to', {'url': reverse('networks_index'),
                                    'permanent': True}),
    url(r'^ChapterPosts', 'redirect_to', {'url': reverse('home'),
                                    'permanent': True}),
    url(r'^ChapterInfo$', 'redirect_to', {'url': reverse('networks_index'),
                                    'permanent': True}),
    url(r'^ChapterInfo/(?P<group_slug>[-\w]+)$', 'redirect_to', {'url': '/networks/%(group_slug)s/',
                                    'permanent': True}),
    url(r'^EditChapter', 'redirect_to', {'url': reverse('networks_index'),
                                    'permanent': True}),
    url(r'^ListChapters', 'redirect_to', {'url': reverse('networks_index'),
                                    'permanent': True}),
    url(r'^ExecTitle', 'redirect_to', {'url': reverse('networks_index'),
                                    'permanent': True}),
    url(r'^ManageEmailForwards', 'redirect_to', {'url': reverse('networks_index'),
                                    'permanent': True}),
    url(r'^MemberInfo', 'redirect_to', {'url': reverse('profiles_index'),
                                    'permanent': True}),
    url(r'^NMTTitle', 'redirect_to', {'url': reverse('national_office'),
                                    'permanent': True}),
    url(r'^NationalOffice', 'redirect_to', {'url': reverse('national_office'),
                                    'permanent': True}),
    url(r'^ListEmailForwards', 'redirect_to', {'url': reverse('networks_index'),
                                    'permanent': True}),
    url(r'^Dashboard', 'redirect_to', {'url': reverse('stats_dashboard'),
                                    'permanent': True}),
    url(r'^ListActivities', 'redirect_to', {'url': reverse('champ_dashboard'),
                                    'permanent': True}),
    url(r'^EditReflection', 'redirect_to', {'url': reverse('champ_dashboard'),
                                    'permanent': True}),
    url(r'^EditActivity', 'redirect_to', {'url': reverse('champ_dashboard'),
                                    'permanent': True}),
    url(r'^EditPurpose', 'redirect_to', {'url': reverse('champ_dashboard'),
                                    'permanent': True}),
    url(r'^ReflectionInfo', 'redirect_to', {'url': reverse('champ_dashboard'),
                                    'permanent': True}),
    url(r'^ActivityInfo', 'redirect_to', {'url': reverse('champ_dashboard'),
                                    'permanent': True}),
    url(r'^ListReflections', 'redirect_to', {'url': reverse('champ_dashboard'),
                                    'permanent': True}),
    url(r'^CHAMP', 'redirect_to', {'url': reverse('champ_dashboard'),
                                    'permanent': True}),
    url(r'^EditYearPlan', 'redirect_to', {'url': reverse('champ_dashboard'),
                                    'permanent': True}),
    url(r'^EditActivityText', 'redirect_to', {'url': reverse('champ_dashboard'),
                                    'permanent': True}),
    )