from django.conf.urls.defaults import *

urlpatterns = patterns('siteutils.shortcuts',
    url(r'^Chapter$', 'redirect_to_reverse', {'url': 'networks_index',
                                    'permanent': True}),
    url(r'^ChapterPosts', 'redirect_to_reverse', {'url': 'home',
                                    'permanent': True}),
    url(r'^ChapterInfo$', 'redirect_to_reverse', {'url': 'networks_index',
                                    'permanent': True}),
    url(r'^ChapterInfo/(?P<group_slug>[-\w]+)$', 'redirect_to', {'url': '/networks/%(group_slug)s/',
                                    'permanent': True}),
    url(r'^EditChapter', 'redirect_to_reverse', {'url': 'networks_index',
                                    'permanent': True}),
    url(r'^ListChapters', 'redirect_to_reverse', {'url': 'networks_index',
                                    'permanent': True}),
    url(r'^ExecTitle', 'redirect_to_reverse', {'url': 'networks_index',
                                    'permanent': True}),
    url(r'^ManageEmailForwards', 'redirect_to_reverse', {'url': 'networks_index',
                                    'permanent': True}),
    url(r'^MemberInfo', 'redirect_to_reverse', {'url': 'profiles_index',
                                    'permanent': True}),
    url(r'^NMTTitle', 'redirect_to_reverse', {'url': 'national_office',
                                    'permanent': True}),
    url(r'^NationalOffice', 'redirect_to_reverse', {'url': 'national_office',
                                    'permanent': True}),
    url(r'^ListEmailForwards', 'redirect_to_reverse', {'url': 'networks_index',
                                    'permanent': True}),
    url(r'^Dashboard', 'redirect_to_reverse', {'url': 'stats_dashboard',
                                    'permanent': True}),
    url(r'^ListActivities', 'redirect_to_reverse', {'url': 'champ_dashboard',
                                    'permanent': True}),
    url(r'^EditReflection', 'redirect_to_reverse', {'url': 'champ_dashboard',
                                    'permanent': True}),
    url(r'^EditActivity', 'redirect_to_reverse', {'url': 'champ_dashboard',
                                    'permanent': True}),
    url(r'^EditPurpose', 'redirect_to_reverse', {'url': 'champ_dashboard',
                                    'permanent': True}),
    url(r'^ReflectionInfo', 'redirect_to_reverse', {'url': 'champ_dashboard',
                                    'permanent': True}),
    url(r'^ActivityInfo', 'redirect_to_reverse', {'url': 'champ_dashboard',
                                    'permanent': True}),
    url(r'^ListReflections', 'redirect_to_reverse', {'url': 'champ_dashboard',
                                    'permanent': True}),
    url(r'^CHAMP', 'redirect_to_reverse', {'url': 'champ_dashboard',
                                    'permanent': True}),
    url(r'^EditYearPlan', 'redirect_to_reverse', {'url': 'champ_dashboard',
                                    'permanent': True}),
    url(r'^EditActivityText', 'redirect_to_reverse', {'url': 'champ_dashboard',
                                    'permanent': True}),
    )