from django.conf.urls.defaults import *

urlpatterns = patterns('siteutils.shortcuts',
    url(r'^Events', 'redirect_to_reverse', {'url': 'events_all',
                                    'permanent': True}),
    url(r'^MonthView/(?P<group_slug>[-\w]+)', 'redirect_to', {'url': '/events/for/networks/network/slug/%(group_slug)s/',
                                    'permanent': True}),
    url(r'^MonthView/(?P<group_slug>[-\w]+)/', 'redirect_to', {'url': '/events/for/networks/network/slug/%(group_slug)s/',
                                    'permanent': True}),
    url(r'^MonthView', 'redirect_to_reverse', {'url': 'events_all',
                                    'permanent': True}),
    url(r'^EditEvent', 'redirect_to_reverse', {'url': 'events_all',
                                    'permanent': True}),
    url(r'^DayView', 'redirect_to_reverse', {'url': 'events_all',
                                    'permanent': True}),
    url(r'^EventInfo', 'redirect_to_reverse', {'url': 'events_all',
                                    'permanent': True}),
    url(r'^Conference', 'redirect_to_reverse', {'url': 'events_all',
                                    'permanent': True}),
    url(r'^EditWhiteboard', 'redirect_to_reverse', {'url': 'events_all',
                                    'permanent': True}),
    url(r'^ListView', 'redirect_to_reverse', {'url': 'events_all',
                                    'permanent': True}),
    url(r'^ListUpcoming', 'redirect_to_reverse', {'url': 'events_all',
                                    'permanent': True}),
    url(r'^TopKeywords', 'redirect_to_reverse', {'url': 'events_all',
                                    'permanent': True}),
    )
