from django.conf.urls.defaults import *
from django.core.urlresolvers import reverse

urlpatterns = patterns('django.views.generic.simple',
    url(r'^Dashboard$', 'redirect_to', {'url': reverse('stats_dashboard'),
                                    'permanent': True}),
    url(r'^About$', 'redirect_to', {'url': reverse('about'),
                                    'permanent': True}),
    url(r'^PrivacyPolicy$', 'redirect_to', {'url': reverse('privacy'),
                                    'permanent': True}),
    url(r'^Home$', 'redirect_to', {'url': reverse('home'),
                                    'permanent': True}),
    url(r'^NewPost$', 'redirect_to', {'url': reverse('topic_new'),
                                    'permanent': True}),
    url(r'^NewPosts$', 'redirect_to', {'url': reverse('topic_since_login'),
                                    'permanent': True}),
    url(r'^TopKeywords$', 'redirect_to', {'url': reverse('topic_cloud'),
                                    'permanent': True}),
    url(r'^Posts$', 'redirect_to', {'url': reverse('home'),
                                    'permanent': True}),
    url(r'^Help$', 'redirect_to', {'url': reverse('about'),
                                    'permanent': True}),
    url(r'^Search$', 'redirect_to', {'url': reverse('search'),
                                    'permanent': True}),
    url(r'^AdvancedSearchResults$', 'redirect_to', {'url': reverse('search'),
                                    'permanent': True}),
    #url(r'^ShowPost/(?P<topic_id>\d+)$', 'redirect_to', {'url': reverse('topic_detail', kwargs={'topic_id': '%(topic_id)d'}),
    #                                'permanent': True}),
    url(r'^ShowPost/(?P<topic_id>\d+)$', 'redirect_to', {'url': '/posts/%(topic_id)s/',
                                                         'permanent': True}),
    url(r'^SignIn$', 'redirect_to', {'url': reverse('acct_login'),
                                    'permanent': True}),
    url(r'^TermsOfUse$', 'redirect_to', {'url': reverse('terms'),
                                    'permanent': True}),
    url(r'^Thanks$', 'redirect_to', {'url': reverse('about'),
                                    'permanent': True}),
    url(r'^Print/(?P<topic_id>\d+)$', 'redirect_to', {'url': '/posts/%(topic_id)s/print/',
                                    'permanent': True}),
    url(r'^Print/(?P<topic_id>\d+)/replies$', 'redirect_to', {'url': '/posts/%(topic_id)s/printreplies/',
                                    'permanent': True}),
    url(r'^AdvancedSearch$', 'redirect_to', {'url': reverse('search'),
                                    'permanent': True}),
    url(r'^FlaggedPosts$', 'redirect_to', {'url': reverse('topic_watchlists'),
                                    'permanent': True}),
    url(r'^EditPostWhiteboard/(?P<topic_id>\d+)$', 'redirect_to', {'url': '/posts/%(topic_id)s/',
                                    'permanent': True}),
    url(r'^FeaturedPosts$', 'redirect_to', {'url': reverse('topic_featured'),
                                    'permanent': True}),
    url(r'^RecentWhiteboards$', 'redirect_to', {'url': reverse('topic_since_login'),
                                    'permanent': True}),
    )
