from django.conf.urls.defaults import *
from django.core.urlresolvers import reverse

urlpatterns = patterns('django.views.generic.simple',
    url(r'^AvailableLists', 'redirect_to', {'url': reverse('communities_index'),
                                    'permanent': True}),
    url(r'^EditList/(?P<group_id>\d+)', 'redirect_to', {'url': '/groups/id/%(group_id)s/',
                                    'permanent': True}),
    url(r'^ListInfo/(?P<group_id>\d+)', 'redirect_to', {'url': '/groups/id/%(group_id)s/',
                                    'permanent': True}),
    url(r'^ListMember', 'redirect_to', {'url': reverse('profiles_index'),
                                    'permanent': True}),
    url(r'^ListMgmt/(?P<group_id>\d+)', 'redirect_to', {'url': '/groups/id/%(group_id)s/',
                                    'permanent': True}),
    url(r'^Mailing', 'redirect_to', {'url': reverse('communities_index'),
                                    'permanent': True}),
    url(r'^MyLists', 'redirect_to', {'url': reverse('communities_index'),
                                    'permanent': True}),
    url(r'^NewList', 'redirect_to', {'url': reverse('new_community'),
                                    'permanent': True}),
    url(r'^SendEmail(?P<group_id>\d+)', 'redirect_to', {'url': '/groups/id/%(group_id)s/',
                                    'permanent': True}),
    url(r'^Unsubscription', 'redirect_to', {'url': reverse('network_unsubscribe'),
                                    'permanent': True}),
    url(r'^MainListSignup', 'redirect_to', {'url': reverse('home'),
                                    'permanent': True}),
    url(r'^MassDelete', 'redirect_to', {'url': reverse('mass_delete'),
                                    'permanent': True}),
    url(r'^MailableLists', 'redirect_to', {'url': reverse('communities_index'),
                                    'permanent': True}),
    url(r'^Projects', 'redirect_to', {'url': reverse('communities_index'),
                                    'permanent': True}),
                            
    )