from django.conf.urls.defaults import *
from django.core.urlresolvers import reverse

urlpatterns = patterns('django.views.generic.simple',
    url(r'^DeleteUser', 'redirect_to', {'url': reverse('profile_edit'),
                                    'permanent': True}),
    url(r'^EditProfile', 'redirect_to', {'url': reverse('profile_edit'),
                                    'permanent': True}),
    url(r'^UserProfile/(?P<profile_id>\d+)$', 'redirect_to', {'url': '/profiles/%(profile_id)s/',
                                    'permanent': True}),
    url(r'^PayDues', 'redirect_to', {'url': reverse('profile_edit'),
                                    'permanent': True}),
    url(r'^ForgotPassword$', 'redirect_to', {'url': reverse('acct_passwd_reset'),
                                    'permanent': True}),
    url(r'^MyPosts$', 'redirect_to', {'url': reverse('profiles_index'),
                                    'permanent': True}),
    url(r'^Profile$', 'redirect_to', {'url': reverse('profiles_index'),
                                    'permanent': True}),
    url(r'^ShowInfo$', 'redirect_to', {'url': reverse('profiles_index'),
                                    'permanent': True}),
    url(r'^SignUp$', 'redirect_to', {'url': reverse('acct_signup'),
                                    'permanent': True}),
    url(r'^SignUp/(?P<chapter_slug>[\w]+)$', 'redirect_to', {'url': '/account/signup/%(chapter_slug)s/',
                                    'permanent': True}),
    url(r'^ChangePicture$', 'redirect_to', {'url': reverse('profile_edit'),
                                    'permanent': True}),
    url(r'^PaymentResult$', 'redirect_to', {'url': reverse('profile_edit'),
                                    'permanent': True}),
    url(r'^UserPosts/(?P<profile_id>\d+)$', 'redirect_to', {'url': '/profiles/%(profile_id)s/',
                                    'permanent': True}),
    url(r'^RegularSignUp$', 'redirect_to', {'url': reverse('acct_signup'),
                                    'permanent': True}),
    )
